---
- name: Process management tasks
  hosts: all
  become: true
  tasks:
    - name: Get a running process
      ignore_errors: true
      command: ps aux | grep fwupd
      register: running_process
   
    - name: Check if the process is running
      debug:
        msg: "Process is running"
      when: running_process.stdout != "fwupd"

    - name: Stop the process if running
      command: kill -9 {{ running_process.stdout.split()[1] }}
      when: running_process.stdout != "fwupd"