---
- name: Installing and running apache
  hosts: all
  become: true
  tasks:
    - name: copy file to target hosts
      copy:
        src: sample.txt
        dest: /tmp/sample.txt
        mode: '0644'
        owner: ubuntu
        group: ubuntu
      