---
- name: Installing and running apache
  hosts: all
  become: true
  tasks:
    - name: Setup apache2 and open firewall port
      apt:
        name: apache2
        state: present
      
    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true
      
    - name: Ensure the firewall is configured to allow HTTP traffic
      ufw:
        rule: allow
        name: 'Apache http allow'
        port: '80'
        proto: tcp
        state: enabled
    - name: Ensure the firewall is configured to allow ssh traffic
      ufw:
        rule: allow
        name: 'ssh allow'
        port: '22'
        proto: tcp
        state: enabled
        
    - name: Restart firewall to apply changes
      command: ufw reload